### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by valincius** [valincius/BlazorScheduler#17]
## Changes
- Deprecates/Removes `BlazorScheduler.Core`
  - Removes the need for having your model implement `BlazorScheduler.Core.IAppointment`
    - Appointments are now components that may be changed dynamically without modifying the original reference
- Typeparam removed from `Scheduler` (and all other components)
- Removes `OnAppointmentClick` callback
- Removes `OnDayClick`
- Day number is no longer clickable by default
- Adds `Appointment` component
  - This component should be rendered under a `<Scheduler />`
  - `OnClick`  callback replaces `Scheduler.OnAppointmentClick`
  - `ChildContent` is rendered on the appointment instead of text, allowing for more customizability
  - `Color` is now a string rather than `System.Drawing.Color`
- Callbacks have all had `MouseEventArgs` removed from their arguments
- Moves `ThemeColor` & `StartDayOfWeek` to `Config`
- `ThemeColor` is now a string
- The header can now be templated (see demo)
- The day component can now be templated (see demo)
- Fixed weekday text to be truncated on smaller devices
- Added configuration values for modifying the "Today" button and the text that shows for overflow appointments.
- Added new demos to show the features and customizations
- Day names are now localized
- Added `Invalidate` method to `Scheduler`
   - This can be called to rerender child components incase you make updates to a template
     - Only necessary for day templates at the moment (see demo)
- Added `OnRequestNewData` action
  - This is called on the first render & whenever the current date changes, so we can send a request and get the appointments for the current date range

## Todo
- [x] Fix weekday text for small devices
- [x] Add ability to customize the header row (Today button, changing month)
- [x] Add ability to customize the Month and Day names, and the "+ n others" text
  - [x] "+ n others"
  - [x] Month names
  - [x] Day names
- [x] Fix broken styling
- [x] Remove commented out code
- [x] New (better) demos
  - [x] Base demo
  - [x] Configuration demo
  - [x] Interactions demo
  - [x] Header template
  - [x] Day template
